### ISSUE TITLE
create invoice when payment is succesful

### ISSUE THREAD

**Issue by hezide** [ORBA/magento2_payupl#3]
Hi,
In configurations, I can choose that "Completed Payment Order Status" will be in "processing" status.
So it changes the status to processing but does not create an invoice.

how can I make it create an invoice automatically when payment is completed?

thanks.

**Comment by michalbiarda** [comment]
Hi @hezide 

Sorry for replying soooo late. We lost focus of this extension for some time but now we're coming back to ongoing development.

Basically, the invoice should be created automatically when the payment notification is consumed. Isn't it working for you this way?

**Comment by hezide** [comment]
Hi @michalbiarda  ,
I no longer use the website and won't be using it anymore.
But as for what I recall, I had to open the order and manually press "Create Invoice".
I can no longer provide further details so if you can't reproduce it, you can close the issue.

Thanks.
